default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: "root"
  password: "password"
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
