import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Read
          <Link href="/mypage/posts">
            <a>this page!</a>
          </Link>
        </h1>
      </main>
    </div>
  );
};

export default Home;
